### ISSUE TITLE
Entity State in Condition not working

### ISSUE THREAD

**Issue by kobelka** [geertmeersman/robonect#207]
I have in home assistant a conditional card.

I want that the card is shown, when the mower is mowing or an error appears.
But first I only test the mowing :-)

With this yaml code condition the card is not showing up:

```
condition: state
entity: lawn_mower.automower_robonect
state: mowing
```

As you see:
![image](https://github.com/user-attachments/assets/9c198696-aa07-48f5-9ac0-a1a39bbfec4c)

**Comment by geertmeersman** [comment]
Hi,

the states are numeric, you can always see the state in the states in the developer tools.

If you would put 2 as a state instead of mowing, it will work.

```
    "lawn_mower": {
      "automower": {
        "name": "Robotic Lawn Mower",
        "state": {
          "0": "Detecting status",
          "1": "Parked",
          "2": "Mowing",
          "3": "Searching for charging station",
          "4": "Charging",
          "5": "Searching",
          "7": "Error",
          "8": "Lost cable signal",
          "16": "Off",
          "17": "Sleeping",
          "18": "Waiting for garage door",
          "98": "Offline (unable to connect)",
          "99": "Unknown"
        },
```

**Comment by kobelka** [comment]
OK, it looks like it works. Thanks for that! But I still think something needs to be changed in the integration. I am being suggested states. Otherwise I would have to look at your post here every time ;-)
![image](https://github.com/user-attachments/assets/063d2a39-3732-4a6b-bfc9-d575da7208fc)

**Comment by geertmeersman** [comment]
Should be fixed in release v2.0.0

**Comment by geertmeersman** [comment]
If all is fine, please close the issue 🙏

**Comment by kobelka** [comment]
I have installed V2.0.0, but the Problem still exists.
 
- Not all states are shown 
- And in the conditional card the conditions does not work with the shown states, only with the numbers

**Comment by geertmeersman** [comment]
Are you using the lawn_mower? As in my case it works fine?
Could you join  on discord?

**Comment by kobelka** [comment]
I never used discord before...how can I find you ?

**Comment by kobelka** [comment]
Ok, I don´t no why but now it is working with the states, but not all statuses are displayed (only 7 from 13)

![image](https://github.com/user-attachments/assets/5deccd50-69d5-401d-af57-7070bf8706d9)

```
          "0": "Detecting status",
          "1": "Parked",
          "2": "Mowing",
          "3": "Searching for charging station",
          "4": "Charging",
          "5": "Searching",
          "7": "Error",
          "8": "Lost cable signal",
          "16": "Off",
          "17": "Sleeping",
          "18": "Waiting for garage door",
          "98": "Offline (unable to connect)",
          "99": "Unknown"
```

**Comment by geertmeersman** [comment]
That's normal, since not all statuses are supported by the lawn_mower standard entity.
I made sure that now the status is not a number anymore but the text state expected by the standard entity.

**Comment by kobelka** [comment]
Ok, thank you 👍
